sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - "node_modules"
install:
    - npm install
script:
    - npm run e2e
