sudo: enabled
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - "node_modules"
install:
    - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    - npm run e2e
